name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SONAR_HOST: https://sonarcloud.io
  SONAR_ORGANIZATION: innovt
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
  SONAR_PROJECTKEY: Innovtt_Innovt.Platform

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.202
        include-prerelease: true
        fetch-depth: 0        
    - name: Setting Workspace
      working-directory: ${{ github.workspace }}
      run: ls -la
    - name: Install dependencies
      working-directory: src
      run: dotnet restore    
    - name: Install Sonnar Scaner        
      run: dotnet tool install -g dotnet-sonarscanner
    - name: Build
      working-directory: src
      run: | 
            dotnet sonarscanner begin /d:sonar.login=$SONAR_TOKEN /d:sonar.host.url=$SONAR_HOST /o:$SONAR_ORGANIZATION /k:"$SONAR_PROJECTKEY" /d:sonar.cs.opencover.reportsPaths="**/testresults/coverage.opencover.xml" /d:sonar.coverage.exclusions=**Test*.cs /d:sonar.cs.vstest.reportsPaths=./testresults/*.trx ;
            dotnet build -c Release
            dotnet test -c Release --logger trx --results-directory ./testresults /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./testresults/coverage.opencover.xml
            dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN